name: 'retail_analytics'
version: '1.0.0'
config-version: 2

profile: 'retail'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_analytics:
    staging:
      +schema: silver_retail
      +materialized: view
      +tags: ['silver', 'staging']
    marts:
      +schema: gold_retail
      +materialized: table
      +tags: ['gold', 'marts']